development:
  adapter: postgresql
  database: beaucoop
  username: beaucoop
  password: beaucoop
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: beaucoop_test
  username: postgres
  host: localhost
  encoding: UTF8
